// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Dtos;

public partial class DtoEmployee
{
    public int EmployeeId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string Title { get; set; }

    public string TitleOfCourtesy { get; set; }

    public DateTime? BirthDate { get; set; }

    public DateTime? HireDate { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string Region { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string HomePhone { get; set; }

    public string Extension { get; set; }

    public byte[] Photo { get; set; }

    public string Notes { get; set; }

    public int? ReportsTo { get; set; }

    public string PhotoPath { get; set; }

    public virtual ICollection<DtoEmployee> InverseReportsToNavigation { get; } = new List<DtoEmployee>();

    public virtual ICollection<DtoOrder> Orders { get; } = new List<DtoOrder>();

    public virtual DtoEmployee ReportsToNavigation { get; set; }
}