// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Dtos;

public partial class DtoOrder
{
    public int OrderId { get; set; }

    public string CustomerId { get; set; }

    public int? EmployeeId { get; set; }

    public DateTime? OrderDate { get; set; }

    public DateTime? RequiredDate { get; set; }

    public DateTime? ShippedDate { get; set; }

    public int? ShipVia { get; set; }

    public decimal? Freight { get; set; }

    public string ShipName { get; set; }

    public string ShipAddress { get; set; }

    public string ShipCity { get; set; }

    public string ShipRegion { get; set; }

    public string ShipPostalCode { get; set; }

    public string ShipCountry { get; set; }

    public virtual DtoCustomer Customer { get; set; }

    public virtual DtoEmployee Employee { get; set; }

    public virtual ICollection<DtoOrderDetail> OrderDetails { get; } = new List<DtoOrderDetail>();

    public virtual DtoShipper ShipViaNavigation { get; set; }
}