// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Dtos;

public partial class DtoRegion
{
    public int RegionId { get; set; }

    public string RegionDescription { get; set; }

    public virtual ICollection<DtoTerritory> Territories { get; } = new List<DtoTerritory>();
}