// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Dtos;

public partial class DtoVwProdCatSup
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public short? UnitsInStock { get; set; }

    public string CategoryName { get; set; }

    public string CompanyName { get; set; }

    public string Country { get; set; }
}