// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class VwProdCatSup
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public short? UnitsInStock { get; set; }

    public string CategoryName { get; set; }

    public string CompanyName { get; set; }

    public string Country { get; set; }
}