using static System.Console;
using static System.Math;

WriteLine($"byte....=>min:{byte.MinValue}");
WriteLine($"byte....=>max:{byte.MaxValue}");
WriteLine($"2^8.Kuvveti - 1 :{Pow(2, 8) - 1}");
WriteLine($"byte....=>(RAM): {sizeof(byte)} Byte");
WriteLine("---------------------");
WriteLine($"ushort..=>min:{ushort.MinValue:0,00}");
WriteLine($"ushort..=>max:{ushort.MaxValue:0,00}");
WriteLine($"2^16.Kuveti - 1 :{Pow(2, 16) - 1:0,00}");
WriteLine($"ushort..=>(RAM): {sizeof(ushort)} Byte");
WriteLine("---------------------");
WriteLine($"uint....=>min:{uint.MinValue:0,00}");
WriteLine($"uint....=>max:{uint.MaxValue:0,00}");
WriteLine($"2^32.Kuvveti - 1 :{Pow(2, 32) - 1:0,00}");
WriteLine($"uint....=>(RAM): {sizeof(uint)} Byte");
WriteLine("---------------------");
WriteLine($"ulong...=>min:{ulong.MinValue:0,00}");
WriteLine($"ulong...=>max:{ulong.MaxValue:0,00}");
WriteLine($"2^64.Kuvveti - 1 :{(ulong)Pow(2, 64) - 1:0,00}");
WriteLine($"ulong...=>(RAM): {sizeof(ulong)} Byte");
WriteLine("---------------------");
WriteLine($"sbyte...=>min:{sbyte.MinValue}");
WriteLine($"sbyte...=>max:{sbyte.MaxValue}");
WriteLine($"2^7.Kuvveti (-):{-Pow(2, 7):0,00}");
WriteLine($"2^7.Kuvveti -1 (+):{Pow(2, 7) - 1:0}");
WriteLine($"sbyte...=>(RAM): {sizeof(sbyte)} Byte");
WriteLine("---------------------");
WriteLine($"short...=>min:{short.MinValue:0,00}");
WriteLine($"short...=>max:{short.MaxValue:0,00}");
WriteLine($"2^15.Kuvveti (-):{-Pow(2, 15):0,00}");
WriteLine($"2^15.Kuvveti -1 (+):{Pow(2, 15) - 1:0,00}");
WriteLine($"short...=>(RAM): {sizeof(short)} Byte");
WriteLine("---------------------");
WriteLine($"int.....=>min:{int.MinValue:0,00}");
WriteLine($"int.....=>max:{int.MaxValue:0,00}");
WriteLine($"2^31.Kuvveti (-):{-Pow(2, 31):0,00}");
WriteLine($"2^31.Kuvveti -1 (+):{Pow(2, 31) - 1:0,00}");
WriteLine($"int.....=>(RAM): {sizeof(int)} Byte");
WriteLine("---------------------");
WriteLine($"long....=>min:{long.MinValue:0,00}");
WriteLine($"long....=>max:{long.MaxValue:0,00}");
WriteLine($"2^63.Kuvveti (-):{-Pow(2, 63):0,00}");
WriteLine($"2^63.Kuvveti -1 (+):{Pow(2, 63) - 1:0,00}");
WriteLine($"long....=>(RAM): {sizeof(long)} Byte");
WriteLine("---------------------");
WriteLine($"char....=>min:{(int)char.MinValue:0,00}");
WriteLine($"char....=>max:{(int)char.MaxValue:0,00}");
WriteLine($"char....=>(RAM): {sizeof(char)} Byte");
WriteLine($"2^16.Kuvveti -1 (+):{Pow(2, 16) - 1:0,00}");
WriteLine("Ondalıklı Olan Sayılar");
WriteLine($"float...=>min:{float.MinValue}");
WriteLine($"float...=>max:{float.MaxValue}");
WriteLine($"float...=>(RAM): {sizeof(float)} Byte");
WriteLine("---------------------");
WriteLine($"double..=>min:{double.MinValue}");
WriteLine($"double..=>max:{double.MaxValue}");
WriteLine($"double..=>(RAM): {sizeof(double)} Byte");
WriteLine("---------------------");
WriteLine($"decimal.=>min:{decimal.MinValue:0,00}");
WriteLine($"decimal.=>max:{decimal.MaxValue:0,00}");
WriteLine($"decimal.=>(RAM): {sizeof(decimal)} Byte");
WriteLine("---------------------");
WriteLine("Mantıksal Veri Tipi");
WriteLine($"bool....=>max: {true}");
WriteLine($"bool....=>min: {false}");
WriteLine($"bool....=>(RAM): {sizeof(bool)} Byte");
WriteLine("---------------------");
WriteLine("Tarih Veri Tipi");
WriteLine($"DateTime=>min:{DateTime.MinValue}");
WriteLine($"DateTime=>max:{DateTime.MaxValue}");
ReadKey();
